vvzvlad/glue_user_app

- src/dashboard.vue
- static/maptest.html
* testing google maps
* updating the dashboard
> Dashboard start (#1)

- package-lock.json
- package.json
- src/dashboard.vue
Подключил компонент vue2-leaflet, а в нём - подключил openstreetmap; добавил это всё на место для карты. Должно закрыть ишью #2
> Dashboard map

- src/main_page.vue
Сделал раскрывающиеся меню
#10
> expand menus

- src/main.js
- webpack.config.js
Починил потерявшиеся маркеры на карте; починил двойной маркер.
#9
> fixed leaflet icons

- src/dashboard.vue
> example for marker click

- src/waste/сontainers.vue
> update containers table

- src/waste/сontainers.vue
> shrink containers table

- src/assets/datafile.json
- src/components/bindetails.vue
- src/components/binstable.vue
- src/waste/сontainers.vue
updated : containers.vue, bindetails.vue
created: binstable.vue, datafile.json
> new component - bins table (binstable.vue) (#1)

- src/waste/components/binstable.vue
Отцентрировал надписи в таблице
#28
> table text centering

- src/assets/marker-active.svg
- src/assets/marker.svg
- src/waste/сontainers.vue
> active markers

- src/safety/video.vue
> update video height

- src/infrastructure/components/energy_management_details.vue
> fix map in details modal

- src/dashboard.vue
> card with image

- src/main_page.vue
> add burger button

- src/common/charts/BaseChart.vue
- src/common/charts/DonutChart.vue
- src/dashboard.vue
- src/waste/сontainers.vue
Сделал пончиковые (donut) диаграммы вместе c легендой. Диаграммы автоматически растягиваются под всю возможную ширину.
> donut charts

- src/common/charts/BarChart.vue
- src/dashboard.vue
> added charts on dashboard, improved responsive

- src/common/charts/BarChart.vue
- src/dashboard.vue
> update dashboard and bar charts

- src/common/charts/BarChart.vue
> fix calc sizes

- src/waste/planning.vue
> route delay

- src/main_page.vue
> fix clipped menu

- src/main_page.vue
- src/parking/components/detail.vue
> fix styles

- src/waste/components/binstable.vue
- src/waste/сontainers.vue
> tables fix

- src/eco_monitoring/stations.vue
> reworked parser

- src/waste/components/binstable.vue
> fix table scroll
